# ??????:
#   <RequestClass>=<ResponseClass>
#   <RequestClass>.<???? ???????>=<???? ??????>[:RULE]
# RULE: EQUALS (?? ?????????) | NOT_EQUALS | IGNORE
# ???????????? ?????? ????????????? ????. ????????? ????: customer.name

CreateUserRequestModel=CreateUserResponseModel
CreateUserRequestModel.username=username
CreateUserRequestModel.password=password:NOT_EQUALS
CreateUserRequestModel.role=role

DepositMoneyRequestModel=DepositMoneyResponseModel
DepositMoneyRequestModel.id=id
DepositMoneyRequestModel.balance=balance

TransferMoneyRequestModel=TransferMoneyResponseModel
TransferMoneyRequestModel.senderAccountId=senderAccountId
TransferMoneyRequestModel.receiverAccountId=receiverAccountId
TransferMoneyRequestModel.amount=amount

UpdateCustomerProfileRequestModel=UpdateCustomerProfileResponseModel
UpdateCustomerProfileRequestModel.name=customer.name